name: Git Tool Runner
# Batch-ID: 1756288665940-0.2048643154371066
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone and Run Tool
        run: |
          git clone https://github.com/hungdz28909-collab/tool.git
          cd tool
            node index.js
      - name: Keep Runner Alive
        run: sleep 21000